[package]
name = "radiucal-admin"
version = "1.7.0"
authors = ["Sean Enck <enckse@voidedtech.com>"]
edition = "2018"

[dependencies]
md4 = "0.8.0"
csv = "1.1"
rand = "0.6.5"
aes-ctr = "0.3.0"
chrono = "0.4.6"
encoding = "0.2"
