# plugins are local to what we do
ignored = ["github.com/epiphyte/radiucal/plugins"]

[[constraint]]
  branch = "master"
  name = "layeh.com/radius"

[[constraint]]
  version = "v1.1.0"
  name = "github.com/epiphyte/goutils"
