# plugins are local to what we do
ignored = ["github.com/epiphyte/radiucal/plugins",
           "github.com/epiphyte/radiucal/core",
           "github.com/epiphyte/radiucal/server"]

[[constraint]]
  branch = "master"
  name = "layeh.com/radius"

[[constraint]]
  version = "v1.2.1"
  name = "github.com/epiphyte/goutils"
