#!/bin/bash
AUTHEM_LIB=/var/lib/authem/
AUTHEM_ETC=/etc/authem/authem.sh

if [ -e $AUTHEM_ETC ]; then
    source $AUTHEM_ETC
fi

AUTHEM_GIT=${AUTHEM_LIB}git/
if [ ! -d $AUTHEM_GIT ]; then
    echo "$AUTHEM_GIT does not exist"
    echo
    echo "> git clone <url> $AUTHEM_GIT"
    echo "> cd $AUTHEM_GIT"
    echo "> git checkout -b <name>"
    echo "> git push --set-upstream origin <name>"
    echo
    echo "authem-sync should then be able to run"
    exit 1
fi

cd $AUTHEM_GIT
git fetch origin
git merge origin/master

echo "commit: "$(git log --pretty=format:'%h' -n 1)
authem-configurator
git push
